from binance.um_futures import UMFutures

# binance API need VPN if you are in US and China, use this in case you cannot run
"""
1000000MOGUSDT,1000BONKUSDT,1000CATUSDT,1000CHEEMSUSDT,1000FLOKIUSDT,1000LUNCUSDT,1000PEPEUSDT,1000RATSUSDT,1000SATSUSDT,1000SHIBUSDT,1000WHYUSDT,1000XECUSDT,1000XUSDT,1INCHUSDT,1MBABYDOGEUSDT,AAVEUSDT,ACEUSDT,ACHUSDT,ACTUSDT,ADAUSDT,AERGOUSDT,AEVOUSDT,AGLDUSDT,AIUSDT,AKTUSDT,ALGOUSDT,ALICEUSDT,ALPACAUSDT,ALPHAUSDT,ALTUSDT,AMBUSDT,ANKRUSDT,APEUSDT,API3USDT,APTUSDT,ARBUSDT,ARKMUSDT,ARKUSDT,ARPAUSDT,ARUSDT,ASTRUSDT,ATAUSDT,ATOMUSDT,AUCTIONUSDT,AVAXUSDT,AXLUSDT,AXSUSDT,BADGERUSDT,BAKEUSDT,BALUSDT,BANANAUSDT,BANDUSDT,BANUSDT,BATUSDT,BBUSDT,BCHUSDT,BEAMXUSDT,BELUSDT,BICOUSDT,BIGTIMEUSDT,BLURUSDT,BLZUSDT,BNBUSDT,BNTUSDT,BNXUSDT,BOMEUSDT,BONDUSDT,BRETTUSDT,BSVUSDT,BSWUSDT,BTCDOMUSDT,BTCUSDT,C98USDT,CAKEUSDT,CATIUSDT,CELOUSDT,CELRUSDT,CETUSUSDT,CFXUSDT,CHESSUSDT,CHILLGUYUSDT,CHRUSDT,CHZUSDT,CKBUSDT,COMBOUSDT,COMPUSDT,COSUSDT,COTIUSDT,COWUSDT,CRVUSDT,CTSIUSDT,CYBERUSDT,DARUSDT,DASHUSDT,DEFIUSDT,DEGENUSDT,DENTUSDT,DIAUSDT,DODOXUSDT,DOGEUSDT,DOGSUSDT,DOTUSDT,DRIFTUSDT,DUSKUSDT,DYDXUSDT,DYMUSDT,EDUUSDT,EGLDUSDT,EIGENUSDT,ENAUSDT,ENJUSDT,ENSUSDT,EOSUSDT,ETCUSDT,ETHFIUSDT,ETHUSDT,ETHWUSDT,FETUSDT,FIDAUSDT,FILUSDT,FIOUSDT,FLMUSDT,FLOWUSDT,FLUXUSDT,FTMUSDT,FXSUSDT,GALAUSDT,GASUSDT,GHSTUSDT,GLMUSDT,GMTUSDT,GMXUSDT,GOATUSDT,GRASSUSDT,GRTUSDT,GTCUSDT,GUSDT,HBARUSDT,HFTUSDT,HIFIUSDT,HIGHUSDT,HIPPOUSDT,HMSTRUSDT,HOOKUSDT,HOTUSDT,ICPUSDT,ICXUSDT,IDUSDT,ILVUSDT,IMXUSDT,INJUSDT,IOSTUSDT,IOTAUSDT,IOTXUSDT,IOUSDT,JASMYUSDT,JOEUSDT,JTOUSDT,JUPUSDT,KASUSDT,KAVAUSDT,KDAUSDT,KEYUSDT,KNCUSDT,KSMUSDT,LDOUSDT,LEVERUSDT,LINAUSDT,LINKUSDT,LISTAUSDT,LITUSDT,LOKAUSDT,LOOMUSDT,LPTUSDT,LQTYUSDT,LRCUSDT,LSKUSDT,LTCUSDT,LUNA2USDT,MAGICUSDT,MANAUSDT,MANTAUSDT,MASKUSDT,MAVIAUSDT,MAVUSDT,MBOXUSDT,MEMEUSDT,METISUSDT,MEWUSDT,MINAUSDT,MKRUSDT,MOODENGUSDT,MORPHOUSDT,MOVRUSDT,MTLUSDT,MYROUSDT,NEARUSDT,NEIROETHUSDT,NEIROUSDT,NEOUSDT,NFPUSDT,NKNUSDT,NMRUSDT,NOTUSDT,NTRNUSDT,NULSUSDT,OGNUSDT,OMGUSDT,OMNIUSDT,OMUSDT,ONDOUSDT,ONEUSDT,ONGUSDT,ONTUSDT,OPUSDT,ORBSUSDT,ORDIUSDT,OXTUSDT,PENDLEUSDT,PEOPLEUSDT,PERPUSDT,PHBUSDT,PIXELUSDT,PNUTUSDT,POLUSDT,POLYXUSDT,PONKEUSDT,POPCATUSDT,PORTALUSDT,POWRUSDT,PYTHUSDT,QNTUSDT,QTUMUSDT,QUICKUSDT,RAREUSDT,RDNTUSDT,REEFUSDT,REIUSDT,RENDERUSDT,RENUSDT,REZUSDT,RIFUSDT,RLCUSDT,RONINUSDT,ROSEUSDT,RPLUSDT,RSRUSDT,RUNEUSDT,RVNUSDT,SAFEUSDT,SAGAUSDT,SANDUSDT,SANTOSUSDT,SCRTUSDT,SCRUSDT,SEIUSDT,SFPUSDT,SKLUSDT,SLERFUSDT,SNXUSDT,SOLUSDT,SPELLUSDT,SSVUSDT,STEEMUSDT,STGUSDT,STMXUSDT,STORJUSDT,STRKUSDT,STXUSDT,SUIUSDT,SUNUSDT,SUPERUSDT,SUSHIUSDT,SWELLUSDT,SXPUSDT,SYNUSDT,SYSUSDT,TAOUSDT,THETAUSDT,THEUSDT,TIAUSDT,TLMUSDT,TNSRUSDT,TOKENUSDT,TONUSDT,TRBUSDT,TROYUSDT,TRUUSDT,TRXUSDT,TURBOUSDT,TUSDT,TWTUSDT,UMAUSDT,UNIUSDT,USDCUSDT,USTCUSDT,UXLINKUSDT,VANRYUSDT,VETUSDT,VIDTUSDT,VOXELUSDT,WAXPUSDT,WIFUSDT,WLDUSDT,WOOUSDT,WUSDT,XAIUSDT,XEMUSDT,XLMUSDT,XMRUSDT,XRPUSDT,XTZUSDT,XVGUSDT,XVSUSDT,YFIUSDT,YGGUSDT,ZECUSDT,ZENUSDT,ZETAUSDT,ZILUSDT,ZKUSDT,ZROUSDT,ZRXUSDT
"""


def custom_sort(item):
    return tuple(item[i] for i in range(len(item)))


um_futures_client = UMFutures()
a = um_futures_client.exchange_info()
coins = []
for i in a["symbols"]:
    if i["status"] == "TRADING" and i["contractType"] == "PERPETUAL":
        coins.append(i["symbol"])


usdt_coin = [s for s in coins if "USDT" in s]
sorted_list = sorted(usdt_coin, key=custom_sort)

print(",".join(sorted_list))  # input to data_processer
